# Generated by Django 2.0.1 on 2018-02-14 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('senha', models.IntegerField(unique=True, verbose_name='Senha')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('atualizado_por', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_core_cadastro_set', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_core_cadastro_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-senha'],
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('brinquedo_qt', models.PositiveIntegerField(default=0, verbose_name='Brinquedos Qtd')),
                ('brinquedo_vl', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Brinquedos Valor')),
                ('bazar_qt', models.PositiveIntegerField(default=0, verbose_name='Artigos de Bazar Qtd')),
                ('bazar_vl', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Artigos de Bazar Valor')),
                ('eletro_qt', models.PositiveIntegerField(default=0, verbose_name='Equipamentos Eletrônicos Qtd')),
                ('eletro_vl', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Equipamentos Eletrônicos Valor')),
                ('relogio_qt', models.PositiveIntegerField(default=0, verbose_name='Relógios Qtd')),
                ('relogio_vl', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Relógios Vlr')),
                ('musical_qt', models.PositiveIntegerField(default=0, verbose_name='Instrumentos Musicais, Mesas e Módulos Qtd')),
                ('musical_vl', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Instrumentos Musicais, Mesas e Módulos Valor')),
                ('vestuario_qt', models.PositiveIntegerField(default=0, verbose_name='Vestuário Qtd')),
                ('vestuario_vl', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Vestuário Valor')),
                ('perfume_qt', models.PositiveIntegerField(default=0, verbose_name='Higiene Pessoal, Perfumes e Cosméticos Qtd')),
                ('perfume_vl', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Higiene Pessoal, Perfumes e Cosméticos Valor')),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Valor Total')),
                ('atualizado_por', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_core_recibo_set', to=settings.AUTH_USER_MODEL)),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Cadastro', verbose_name='Cadastro')),
                ('criado_por', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_core_recibo_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
    ]
